openapi: 3.1.0
info:
  title: Sports Club Management - Admin API
  version: 1.0.0
  description: Administrative management endpoints
  contact:
    name: API Support
    email: support@sportsclub.example.com

servers:
  - url: https://your-app.vercel.app/api
    description: Production server

tags:
  - name: User Management
    description: User and role management
  - name: Club Management
    description: Club administration
  - name: Feature Flags
    description: Feature flag management

paths:
  /admin/users:
    post:
      tags:
        - User Management
      summary: Create user
      description: Create a new user with specified role
      operationId: createUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - role
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                role:
                  type: string
                  enum: [admin, coach, athlete, parent]
                clubId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        format: uuid
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /admin/clubs:
    post:
      tags:
        - Club Management
      summary: Create club
      description: Create a new club
      operationId: createClub
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - sportType
              properties:
                name:
                  type: string
                sportType:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Club created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    get:
      tags:
        - Club Management
      summary: List all clubs
      description: Get all clubs in the system
      operationId: listClubs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Clubs retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /admin/feature-flags:
    get:
      tags:
        - Feature Flags
      summary: List feature flags
      description: Get all feature flags
      operationId: listFeatureFlags
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Feature flags retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        enabled:
                          type: boolean
                        rolloutPercentage:
                          type: number
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    put:
      tags:
        - Feature Flags
      summary: Update feature flag
      description: Update feature flag configuration
      operationId: updateFeatureFlag
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                enabled:
                  type: boolean
                rolloutPercentage:
                  type: number
                  minimum: 0
                  maximum: 100
      responses:
        '200':
          description: Feature flag updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error:
                type: object

    ForbiddenError:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error:
                type: object

security:
  - bearerAuth: []
