openapi: 3.1.0
info:
  title: Sports Club Management - Parent Portal API
  version: 1.0.0
  description: Parent portal and monitoring endpoints
  contact:
    name: API Support
    email: support@sportsclub.example.com

servers:
  - url: https://your-app.vercel.app/api
    description: Production server

tags:
  - name: Parent Portal
    description: Parent monitoring and connections

paths:
  /parent/dashboard:
    get:
      tags:
        - Parent Portal
      summary: Get parent dashboard data
      description: Returns connected athletes and their information
      operationId: getParentDashboard
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard data retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      athletes:
                        type: array
                        items:
                          type: object
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /parent/connections:
    post:
      tags:
        - Parent Portal
      summary: Request athlete connection
      description: Request to connect with an athlete
      operationId: requestConnection
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - athleteId
                - relationship
              properties:
                athleteId:
                  type: string
                  format: uuid
                relationship:
                  type: string
                  enum: [father, mother, guardian]
      responses:
        '200':
          description: Connection requested
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              error:
                type: object

security:
  - bearerAuth: []
